version: '3'

services:

  nginx:
    image: nginx
    volumes:
      - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/nginx/blog.conf:/etc/nginx/webapps/blog.conf
    ports:
      - "80:80"
      - "443:443"
    links:
      - ghost
    restart: always

  ghost:
    build: ./ghost
    volumes:
      - ghost:/var/lib/ghost
    environment:
      - NODE_ENV=production
    restart: always

volumes:
  ghost: